consul:
  token:
  address: http://consul-agent-1:8500
election:
  enabled:
    - my-service
  services:
    my-service:
      id: my-service1
      key: service/my-service
      token:
      serviceChecks:
        - service:election1
      primaryTag: primary
      execOnPromote: '/bin/echo I am da boss'
      execOnDemote: '/bin/echo I am no longer da boss'
